# Generated by Django 6.1 on 2026-09-17 05:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table_comment': 'Categorías de actividades comunitarias',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table_comment': 'Catálogo de comunas y regiones para normalizar ubicaciones de actividades',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table_comment': 'Catálogo de habilidades que pueden tener los voluntarios',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(help_text='Dirección o punto de encuentro', max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('cupos_maximos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('en_progreso', 'En Progreso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='publicada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='Voluntariado_actividades_comunitarias.categoria')),
            ],
            options={
                'db_table_comment': 'Actividades comunitarias ofrecidas por organizaciones',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada por el Voluntario')], default='pendiente', max_length=20)),
                ('asistio', models.BooleanField(default=False, help_text='Confirmación de asistencia tras realizar la actividad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Voluntariado_actividades_comunitarias.actividad')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table_comment': 'Inscripciones de voluntarios a actividades',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Voluntariado_actividades_comunitarias.inscripcion')),
            ],
            options={
                'db_table_comment': 'Historial de cambios de estado de las inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField()),
                ('contacto_email', models.EmailField(max_length=254)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizaciones_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table_comment': 'Organizaciones que ofrecen actividades comunitarias',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='Voluntariado_actividades_comunitarias.organizacion'),
        ),
        migrations.CreateModel(
            name='PerfilVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rut_o_dni', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('habilidades', models.TextField(blank=True, help_text='Ej: Primeros auxilios, carpintería, docencia...')),
                ('disponibilidad', models.CharField(blank=True, help_text='Ej: Fines de semana, tardes...', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_voluntario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table_comment': 'Perfil de voluntarios con información adicional',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(help_text='Escala de 1 a 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='Voluntariado_actividades_comunitarias.actividad')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table_comment': 'Reseñas de actividades por voluntarios',
            },
        ),
    ]
